# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4538dc16e2d79fac9b7b4c41df32539bf833d7768b0a090c6f37032d79e8721e04c741b72a2bf7eebcf7878a1c162601bd7dc5f236bf407f3fb9d649a60a5dbc

test:
  secret_key_base: ff616fbfc383f353f3bdc4670b5c825407f6658fc903d284581c90435373479e7e1092d28398bf39e1c2b719d0c6aee28e89efa13e3f2013240be996285c6ef1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
